Extensive admin
stuysu/stuyactivities.org pull request #754
Opened 2023-12-29 22:08 UTC by GandyT

2023-12-29 22:08 UTC, GandyT commented
Corresponding backend pull request:
https://github.com/stuysu/api.stuyactivities.org/pull/762

2023-12-29 23:49 UTC, TheEgghead27 reviewed
Not approving for merge until https://github.com/stuysu/api.stuyactivities.org/pull/762 is done, and I would like to test the interface on beta branch first

2023-12-29 23:49 UTC, TheEgghead27 commented on src/comps/pages/admin/AdminMeetingCard.js
> +const AdminMeetingCard = ({
Normally I would encourage reuse of the normal MeetingCard but hey if it works it works; will deploy to the beta domain for testing

2023-12-30 04:15 UTC, TheEgghead27 requested changes
Failed to test

2023-12-30 04:15 UTC, TheEgghead27 commented on src/pages/admin/manageclubs.js
> +							<AdminMeetingCard
Can't seem to get this to show up on https://beta.stuyactivities.org/admin/manageclubs, even after adding a new meeting with a room set in the future.

2024-01-01 17:34 UTC, TheEgghead27 approved these changes

2024-01-01 19:10 UTC, merged